# Trigger on changes to the "main" branch
trigger:
- main

# Trigger for PRs that target the "main" branch
pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
 - task: GoTool@0
  inputs:
    version: '1.17.2'
  displayName: Specify Go version

- script: |
    ./run-tests.sh --remote --in-proc
  displayName: Build Run tests
