name: 'Conda'
description: 'Builds and (optionally) publishes conda package'
inputs:
  ANACONDA_TOKEN:
    description: 'Token for pushing to anaconda.org'
    required: true
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@e81abac10ce2c37423b54eae5af93aa3b4d3475c
      with:
        activate-environment: mrd-storage-server-build
        environment-file: conda/environment.yml
        python-version: 3.9
        auto-activate-base: false
    - name: Build conda package
      shell: bash -l {0}
      working-directory: conda
      run: |
        export GIT_DESCRIBE_TAG="${GITHUB_REF##*/}"
        ./package.sh
        echo "Packages built: $(find build_pkg -name mrd-storage-server*.tar.bz2)"
    - name: Push conda package
      shell: bash -l {0}
      if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      working-directory: conda
      run: |
        ./publish_package.sh -u ismrmrd -t ${{ inputs.ANACONDA_TOKEN }} -p `find build_pkg -name mrd-storage-server*.tar.bz2`
