name: 'Conda'
description: 'Builds and (optionally) publishes conda package'
inputs:
  ANACONDA_TOKEN:
    description: 'Token for pushing to anaconda.org'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v4
      id: setup-go
      with:
        go-version-file: 'go.mod'

    - shell: bash
      run: |
        # Creating a bash login shell (required to activate the conda environment
        # created below) significantly changes the $PATH variable on macos, which
        # results in the wrong version of Go being chosen. So we capture the directory
        # and prepend it to $PATH after the login shell has initialized below.
        go_install_path=$(dirname "$(which go)")
        echo "GO_INSTALL_PATH=${go_install_path}" >> $GITHUB_ENV

    - uses: conda-incubator/setup-miniconda@e81abac10ce2c37423b54eae5af93aa3b4d3475c
      with:
        activate-environment: mrd-storage-server-build
        environment-file: conda/environment.yml
        python-version: 3.9
        auto-activate-base: false

    - name: Build conda package
      shell: bash -l {0}
      working-directory: conda
      run: |
        export GIT_DESCRIBE_TAG="${GITHUB_REF##*/}"
        export PATH=${GO_INSTALL_PATH}:${PATH}
        ./package.sh
        echo "Packages built: $(find build_pkg -name mrd-storage-server*.tar.bz2)"

    - name: Push conda package
      shell: bash -l {0}
      if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
      working-directory: conda
      run: |
        ./publish_package.sh -u ismrmrd -t ${{ inputs.ANACONDA_TOKEN }} -p `find build_pkg -name mrd-storage-server*.tar.bz2`
